version: '3.8'
services:
  nexus:
    image: sonatype/nexus3
    environment:
      NEXUS_SECURITY_RANDOMPASSWORD: 'false'
    volumes:
      - ./nexus.properties:/nexus-data/etc/nexus.properties
    ports:
      - '8081:8081'

  client:
    build: .
    depends_on:
      - nexus
    volumes:
      - .:/go/src/github.com/kaizendorks/nexus-go-client
